package com.app.model;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

@Entity
@Table(name = "account")
public class Account implements Serializable {
    @Id
    @Column(name = "acc_id")
    private Integer id; //should be generated by some logic

    @Column(name = "acc_balance")
    private Double balance;

    @Column(name = "acc_type")
    private String type; //saving / current

    @Column(name = "acc_createdOn")
    private Date createdOn;

    private Customer customer_id;

    public Account() {
    }

    public Account(Integer id, Double balance, String type, Date createdOn, Customer customer_id) {
        this.id = id;
        this.balance = balance;
        this.type = type;
        this.createdOn = createdOn;
        this.customer_id = customer_id;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Double getBalance() {
        return balance;
    }

    public void setBalance(Double balance) {
        this.balance = balance;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public Customer getCustomer_id() {
        return customer_id;
    }

    public void setCustomer_id(Customer customer_id) {
        this.customer_id = customer_id;
    }
}

