package com.app.model;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

@Entity
@Table(name = "account")
public class Account implements Serializable {
    @Id
   // @Column(name = "acc_id")
    private Integer id; //should be generated by some logic

    @Column(name = "acc_balance")
    private Double balance;

    @Column(name = "acc_type")
    private String type; //saving / current

    @Column(name = "acc_createdOn")
    private Date createdOn;

    @ManyToOne
    @JoinColumn(name = "customer_id")
    private  Customer customer;

    public Account() {
    }

    public Account(Integer id, Double balance, String type, Date createdOn) {
        this.id = id;
        this.balance = balance;
        this.type = type;
        this.createdOn = createdOn;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Double getBalance() {
        return balance;
    }

    public void setBalance(Double balance) {
        this.balance = balance;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Override
    public String toString() {
        return "Account{" +
                "id=" + id +
                ", balance=" + balance +
                ", type='" + type + '\'' +
                ", createdOn=" + createdOn +
                '}';
    }
}

