package com.app.model;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

@Entity
@Table(name = "account")
public class Account implements Serializable {
    @Id
    // @Column(name = "acc_id")
    private String id; //should be generated by some logic

    @Column(name = "acc_balance")
    private Double balance;

    @Column(name = "acc_type")
    private String type; //saving / current

    @Column(name = "acc_createdOn")
    private Date createdOn;

    @ManyToOne
    @JoinColumn(name = "customer_id", referencedColumnName = "customer_id")
    private Customer customer;

    public Account() {
    }

    public Account(String id, Double balance, String type, Date createdOn, Customer customer) {
        this.id = id;
        this.balance = balance;
        this.type = type;
        this.createdOn = createdOn;
        this.customer = customer;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Double getBalance() {
        return balance;
    }

    public void setBalance(Double balance) {
        this.balance = balance;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

//    @Override
//    public String toString() {
//        return "Account{" +
//                "id=" + id +
//                ", balance=" + balance +
//                ", type='" + type + '\'' +
//                ", createdOn=" + createdOn +
//                ", customer=" + customer +
//                '}';
//    }
}

